# Generated by Django 5.2.7 on 2025-11-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='estado',
            field=models.CharField(default='offline', max_length=50),
        ),
    ]
