# Generated by Django 5.2.9 on 2025-12-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_subcategoria_variable_subcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='tipo',
            field = models.CharField(max_length=10,default="FLOAT32")
        ),
    ]
