# Generated by Django 5.2.9 on 2025-12-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20251211_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='tipo',
            field=models.CharField(choices=[('UTF8', 'UTF8'), ('INT16U', 'INT16U'), ('INT32U', 'INT32U'), ('DATETIME', 'DATETIME'), ('FLOAT32', 'FLOAT32'), ('4Q_FP_PF', '4Q_FP_PF'), ('FLOAT32/INT32U', 'FLOAT32/INT32U'), ('BITMAP', 'BITMAP'), ('INT64', 'INT64')], default='FLOAT32', max_length=20),
        ),
    ]
