# Generated by Django 5.2.9 on 2026-01-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_variable_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='id_modbus',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
