# Generated by Django 5.2.9 on 2026-01-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_equipo_id_modbus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
        migrations.AddConstraint(
            model_name='equipo',
            constraint=models.UniqueConstraint(fields=('ip', 'id_modbus'), name='unique_ip_modbus'),
        ),
    ]
