# Generated by Django 5.2.9 on 2026-01-03 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_equipo_ip_equipo_unique_ip_modbus'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='sistema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='api.sistema'),
        ),
    ]
