"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from corsheaders.defaults import default_headers
from pathlib import Path
import os
import environ

# Initialise environment variables
env = environ.Env()
environ.Env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY_DJANGO')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG_DJANGO')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS_DEV', default=['localhost', '127.0.0.1'])


# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

PROJECT_APPS = [
    'api.apps.ApiConfig'
]

THIRD_PARTY_APPS = [
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'ckeditor',
    'ckeditor_uploader',
    'channels'
]

INSTALLED_APPS = PROJECT_APPS + THIRD_PARTY_APPS + DJANGO_APPS

CKAEDITOR_CONFIGS = {
    'default': {            
        'toolbar': 'custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['RemoveFormat', 'Source'],
        ],
        'height': 300,
        'width': '100%',    
        'autoParagraph': False
    },
}

CKEDITOR_UPLOAD_PATH = "/media/"

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',  # ← ¡Esta es la que falta!
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "dist")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'core.wsgi.application'
ASGI_APPLICATION = 'core.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB'),
        'USER': os.getenv('POSTGRES_USER'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
        'HOST': os.getenv('POSTGRES_HOST'),
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_ROOT = BASE_DIR / "staticfiles"

STATIC_URL = '/assets/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

STATICFILES_DIRS = [ os.path.join(BASE_DIR, 'dist', 'assets'),
]



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    # --- PERMISOS ---
    # Permite el acceso sin restricciones a todos los endpoints por defecto.
    # Esto es ideal para desarrollo, pero debe cambiarse a algo más seguro
    # como 'rest_framework.permissions.IsAuthenticated' para producción.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],

    # --- AUTENTICACIÓN ---
    # Al no especificar 'rest_framework.authentication.SessionAuthentication',
    # evitamos la necesidad de tokens CSRF para las peticiones POST/PUT/DELETE
    # desde nuestro frontend de React. Dejamos esta lista vacía para que
    # no se aplique ninguna autenticación por defecto.
    'DEFAULT_AUTHENTICATION_CLASSES': [],
}

CORS_ORIGIN_WHITELIST = env.list('CORS_ORIGIN_WHITELIST_DEV')
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS_DEV')

if not DEBUG:
    ALLOWED_HOSTS = env.list('ALLOWED_HOSTS_PROD')
    CORS_ORIGIN_WHITELIST = env.list('CORS_ORIGIN_WHITELIST_PROD')
    CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS_PROD')


CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS_DEV')

CORS_ALLOW_HEADERS = list(default_headers) + env.list('CORS_ALLOW_HEADERS_DEV', default=["content-type"])

CORS_ALLOW_METHODS = env.list('CORS_ALLOW_METHODS_DEV')

CORS_ALLOW_CREDENTIALS = True

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "handlers": {
        "estado_equipos_file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": "estado_equipos.log",
            "formatter": "simple",
        },

        "estado_equipos_debug_file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": "estado_equipos_debug.log",
            "formatter": "simple",
        },

        "estado_equipos_error_file": {
            "level": "ERROR",
            "class": "logging.FileHandler",
            "filename": "estado_equipos_error.log",
            "formatter": "simple",
        },
    },

    "formatters": {
        "simple": {
            "format": "[{asctime}] {levelname} {name}: {message}",
            "style": "{",
        },
    },

    "loggers": {
        "estado_equipos": {
            "handlers": [
                "estado_equipos_file",
                "estado_equipos_debug_file",
                "estado_equipos_error_file",
            ],
            "level": "DEBUG", 
            "propagate": False,
        },
        "opcua": {
        "handlers": [],
        "level": "WARNING",
        "propagate": False,
        },
        "opcua.client": {
            "handlers": [],
            "level": "WARNING",
            "propagate": False,
        },
        "opcua.ua": {
            "handlers": [],
            "level": "WARNING",
            "propagate": False,
        },
        "opcua.uaprotocol": {
            "handlers": [],
            "level": "WARNING",
            "propagate": False,
        },
        "opcua.binary": {
            "handlers": [],
            "level": "WARNING",
            "propagate": False,
        },


        "pymodbus": {
            "handlers": [],
            "level": "CRITICAL",
            "propagate": False,
        },
        "pymodbus.client": {
            "handlers": [],
            "level": "CRITICAL",
            "propagate": False,
        },
    }
}