# Imagen base
FROM node:22.12.0-alpine

# Crear directorio de trabajo
WORKDIR /app

# Instalar dependencias
COPY package*.json ./
RUN npm install



# Exponer puerto de desarrollo
EXPOSE 3000

# Comando por defecto
CMD ["npm", "run", "dev"]