
services:
  dbInflux:
    image: influxdb:2.7
    environment:
      - INFLUX_INIT_MODE=setup
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUX_ORG=${INFLUX_ORG}
      - INFLUX_BUCKET=${INFLUX_BUCKET}
    volumes:
      - influx_data:/var/lib/influxdb
    ports:
      - "8086:8086"

  dbPostgres:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.django
    command: daphne -b 0.0.0.0 -p 8000 core.asgi:application
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - dbInflux
      - dbPostgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.react
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true  # para hot reload en Docker

volumes:
  influx_data:
  postgres_data: