# Imagen base
FROM python:3.11-slim

# Evita archivos pyc y buffers
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y \
    iputils-ping \
    default-libmysqlclient-dev \
    build-essential \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*
    
# Crear directorio de trabajo
WORKDIR /app
ENV PYTHONPATH="${PYTHONPATH}:/app"
# Instalar dependencias
COPY requirements.txt .
COPY ./packages/ /packages/
RUN pip install --find-links=/packages -r requirements.txt


# Comando por defecto (puede ser override en docker-compose)
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]